"""
Stage 4 — GitHub
Initialises git in the workspace, creates a feature branch, commits all files,
pushes to GitHub, and opens a Pull Request via the GitHub REST API.
"""
import re
import subprocess
from pathlib import Path

import requests

from .config import Config
from .logger import get_logger

logger = get_logger(__name__)


class GitHubClient:
    API = "https://api.github.com"

    def __init__(self):
        self.token = Config.GITHUB_TOKEN
        self.repo = Config.GITHUB_REPO  # owner/repo
        self.default_branch = Config.GITHUB_DEFAULT_BRANCH
        self.headers = {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json",
        }

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _git(self, cmd: str, cwd: Path, check: bool = True) -> subprocess.CompletedProcess:
        result = subprocess.run(
            cmd, shell=True, cwd=cwd, capture_output=True, text=True
        )
        if check and result.returncode != 0:
            raise RuntimeError(
                f"git command failed: {cmd}\n"
                f"STDOUT: {result.stdout}\nSTDERR: {result.stderr}"
            )
        return result

    def _branch_exists_on_remote(self, branch: str) -> bool:
        url = f"{self.API}/repos/{self.repo}/branches/{branch}"
        resp = requests.get(url, headers=self.headers, timeout=30)
        return resp.status_code == 200

    def _detect_default_branch(self) -> str:
        url = f"{self.API}/repos/{self.repo}"
        resp = requests.get(url, headers=self.headers, timeout=30)
        if resp.ok:
            return resp.json().get("default_branch", self.default_branch)
        return self.default_branch

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def push_and_create_pr(
        self,
        workspace_dir: str,
        jira_key: str,
        summary: str,
        requirements: str,
    ) -> dict:
        workspace = Path(workspace_dir)

        # Build branch name
        safe = re.sub(r"[^a-zA-Z0-9\-]", "-", summary.lower())[:40].strip("-")
        branch = f"feature/{jira_key.lower()}-{safe}"

        base_branch = self._detect_default_branch()

        # Embed token in remote URL (never pushed to a public repo history)
        remote_url = f"https://x-access-token:{self.token}@github.com/{self.repo}.git"

        # Init git
        self._git("git init", workspace)
        self._git('git config user.email "ai-pipeline@automated.local"', workspace)
        self._git('git config user.name "AI Pipeline"', workspace)

        # Ensure we can reach remote; set it (remove old if any)
        self._git("git remote remove origin", workspace, check=False)
        self._git(f"git remote add origin {remote_url}", workspace)

        # Fetch the base branch so we can branch from it (avoids unrelated history)
        fetch = self._git(
            f"git fetch origin {base_branch}", workspace, check=False
        )
        if fetch.returncode == 0:
            self._git(f"git checkout -b {branch} origin/{base_branch}", workspace)
        else:
            # Remote is empty or branch doesn't exist — just create orphan
            self._git(f"git checkout --orphan {branch}", workspace)

        # Stage & commit (exclude any .git dir that might exist in sub-dirs)
        self._git("git add -A", workspace)
        commit_msg = (
            f"feat({jira_key}): AI-generated web app\n\n"
            f"Auto-generated by the AI pipeline from Jira story {jira_key}.\n"
            f"Story summary: {summary}"
        )
        self._git(f'git commit -m "{commit_msg}"', workspace)

        # Push
        self._git(f"git push -u origin {branch}", workspace)
        logger.info(f"Pushed branch: {branch}")

        # Create PR via GitHub API
        pr_body = (
            f"## Auto-generated by AI Pipeline\n\n"
            f"**Jira Story:** `{jira_key}`\n\n"
            f"### Requirements\n\n```\n{requirements[:3000]}\n```\n\n"
            f"### What was built\n"
            f"This PR was automatically generated by the AI pipeline.\n\n"
            f"### Tests\n"
            f"Unit tests were written and executed. See `test-results.txt` for details.\n"
        )
        payload = {
            "title": f"[{jira_key}] AI-Generated Web App — {summary[:60]}",
            "head": branch,
            "base": base_branch,
            "body": pr_body,
        }
        resp = requests.post(
            f"{self.API}/repos/{self.repo}/pulls",
            json=payload,
            headers=self.headers,
            timeout=30,
        )
        resp.raise_for_status()
        pr = resp.json()
        logger.info(f"PR created: {pr['html_url']}")

        return {
            "branch": branch,
            "pr_url": pr["html_url"],
            "pr_number": pr["number"],
        }
